name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g. v1.2.0)'
        required: true
        default: 'v0.0.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) Get the code – fetch full history so we can create/push tags
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0          # IMPORTANT: need history to create a tag

    # 2) JDK 17 for the Gradle build
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # (Gradle wrapper already committed; if not, you can add a step to generate it.)
    # 3) Build the release APK
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # 4) Create & push the tag that the Release will use
    - name: Create and push tag
      run: |
        git config --global user.name  "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag "${{ inputs.tag_name }}"
        git push origin "${{ inputs.tag_name }}"

    # 5) Publish a GitHub Release with the APK attached
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name:               ${{ inputs.tag_name }}   # use the tag we just created
        release_name:           ${{ inputs.tag_name }}   # same label for the Release
        generate_release_notes: true
        files: app/build/outputs/apk/release/app-release-unsigned.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
